### ISSUE TITLE
serialized JSON parsing

### ISSUE THREAD

**Issue by g3kr** [aws-samples/amazon-ecs-firelens-examples#20]
I am using the https://github.com/aws-samples/amazon-ecs-firelens-examples/blob/master/examples/fluent-bit/parse-json/extra.conf to parse a JSON field in my log message. This is my log message before parsing:

> {
>     "container_id": "14927aae39875c1cbdae3e41e6a25b19968aba3f24f09404e76190ef61670202",
>     "container_name": "/ecs-LogisticsLDWtest-Logistics-17-LogisticsLDWtest-Logistics-cef884afc6c2dbe0db01",
>     "ec2_instance_id": "i-0a1e58472dc0e9e96",
>     "ecs_cluster": "LDWtest-Logistics",
>     "ecs_task_arn": "arn:aws:ecs:us-west-2:418338086575:task/5372b32a-0894-464d-9da1-601ba33fe77d",
>     "ecs_task_definition": "LogisticsLDWtest-Logistics:5",
>     "log": "{\"thread\":\"http-nginx-8080-exec-3\",\"level\":\"INFO\",\"loggerName\":\"com.enterprise.cloud.Logistics.api.v1.KafkaConsumerV1\",\"reqMsg\":\"{\\\"requestId\\\" : \\\"45da14d9-bbb2-4906-988c-9e8aead17f59\\\", \\\"message\\\" : \\\"Request to list consumer details.\\\"}\",\"endOfBatch\":false,\"loggerFqcn\":\"org.apache.log4j.Category\",\"instant\":{\"epochSecond\":1578674283,\"nanoOfSecond\":74902000},\"contextMap\":{},\"threadId\":23,\"threadPriority\":5}\r",
>     "source": "stdout"
> }

Then with JSON parsing it looks like this:

> {
>     "container_id": "14927aae39875c1cbdae3e41e6a25b19968aba3f24f09404e76190ef61670202",
>     "container_name": "/ecs-LogisticsLDWtest-Logistics-17-LogisticsLDWtest-Logistics-cef884afc6c2dbe0db01",
>     "contextMap": {},
>     "ec2_instance_id": "i-0a1e58472dc0e9e96",
>     "ecs_cluster": "LDWtest-Logistics",
>     "ecs_task_arn": "arn:aws:ecs:us-west-2:418338086575:task/5372b32a-0894-464d-9da1-601ba33fe77d",
>     "ecs_task_definition": "LogisticsLDWtest-Logistics:5",
>     "endOfBatch": false,
>     "instant": {
>         "epochSecond": 1578690446,
>         "nanoOfSecond": 571551000
>     },
>     "level": "INFO",
>     "loggerFqcn": "org.apache.log4j.Category",
>     "loggerName": "com.enterprise.cloud.Logistics.api.v1.KafkaConsumerV1",
>     "reqMsg": "{\"requestId\" : \"45da14d9-bbb2-4906-988c-9e8aead17f59\", \"message\" : \"Request to list consumer details.\"}",
>     "source": "stdout",
>     "thread": "http-nginx-8080-exec-3",
>     "threadId": 23,
>     "threadPriority": 5
> }

The reqMsg field is JSON in itself and I am not sure why this is not getting formatted as JSON. Is there a different parser I need to use or a different regex to parse this? Any help is appreciated.

**Comment by PettitWesley** [comment]
@g3kr Double escaped JSON is difficult...

There are some issues for this on Fluent Bit, for example: https://github.com/fluent/fluent-bit/issues/1044

I think the solution might be doing something like this:
```
[PARSER]
    Name        docker
    Format      json
    # Command      |  Decoder | Field | Optional Action
    # =============|==================|=================
    Decode_Field_As   escaped    log
    Decode_Field_As   escaped    reqMsg
```

**Comment by PettitWesley** [comment]
Please post back and let me know if you get something working.

**Comment by rimantoro** [comment]
I do have the same problem.

I'm using uber-go/zap for my logging in app layer. The log formatter in valid raw json, but seem different if fluentbit gather the log from docker/container.

This is the fluentd log inside container from stdout

```
[0] lucent_svc.local: [1578975835.000000000, {"source"=>"stderr", "log"=>"{"level":"info","ts":1578975835.8050892,"caller":"middleware/echo-middleware.go:222","msg":"success","log":{"error":{"Key":"","Type":26,"Integer":0,"String":"","Interface":null},"host":"0.0.0.0:8098","human_latency":"244.7046ms","id":"WBqZZtNemtoAyeEI6xPIQw96hn7aew4T","latency":244704600,"method":"POST","path":"/api/v1/login","protocol":"HTTP/1.1","query_params":"","remote_ip":"172.18.0.1","request":{"identifier":"user1@mxxxx.com","password":"mypassword"},"response":{"message":"success","payload":{"expires_in":60,"token":"myjwttoken"},"rc":"00","sign":"mysignature"},"status":200,"time":1578975835805046300,"uri":"/api/v1/login","user_agent":"insomnia/7.0.6"}}", "container_id"=>"1fb2bc8dbf7338842b226686937a4663ac509827e52c6ead418844c84b5ecc80", "container_name"=>"/api.lucent.loc"}]
```

The ```log``` value is look like escaped json string but without ```\"``` and is not mapped correctly in elasticsearch.

This is my config 

fluent-bit.conf
```
[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name      forward
    Listen    0.0.0.0
    Port      24224

[OUTPUT]
    Name stdout
    Match *

```

parsers.conf
```
[PARSER]
    Name        docker
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S %z
    Time_Keep   On
    # Command       |  Decoder  | Field | Optional Action   |
    # ==============|===========|=======|===================|
    Decode_Field_As    escaped  log
    # Decode_Field_As escaped_utf8 log do_next
    # Decode_Field_As json log
    # Decode_Field_As escaped log

```

As you look at parsers.conf, I've try multiple combination of decoder with no luck.

As other information, I'm running fluentbit as container within docker-compose.

```
version : '3'

services:
  lucent:
    build: .
    container_name: "api.mysvc.loc"
    ports:
      - 9000:9000
    image: mysvc:latest
    volumes:
      - ./config.yaml:/app/config.yaml
    depends_on:
      - fluentbit
    logging:
      driver: fluentd
      options:
        tag: "mysvc.local"
  
  fluentbit:
    image: fluent/fluent-bit:1.2-debug # I've also try 1.3
    container_name: "flb.mysvc.loc"
    ports:
      - 24224:24224
      - 24224:24224/udp
    volumes:
      - ./deploy/fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./deploy/fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf

networks: 
  default:
    external:
      name: my-shared-network
```
